name: Rollback n8n

on:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Rollback VM
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            set -e

            cd ~/n8n-deployment

            PREV=$(cat .last_good_commit)

            echo "Rolling back to $PREV"

            git reset --hard $PREV

            docker compose up -d

            docker exec n8n-deployment-n8n-1 \
              n8n import:workflow \
              --separate \
              --input=/workflows